CREATE TABLE IF NOT EXISTS `order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '订单ID',
  `order_no` VARCHAR(50) UNIQUE NOT NULL COMMENT '订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `worker_id` BIGINT COMMENT '服务人员ID',
  `service_item_id` BIGINT NOT NULL COMMENT '服务项目ID',
  `service_name` VARCHAR(100) NOT NULL COMMENT '服务名称',
  `service_price` DECIMAL(10,2) NOT NULL COMMENT '服务价格',
  `service_time` DATETIME COMMENT '预约服务时间',
  `service_address` VARCHAR(255) COMMENT '服务地址',
  `service_duration` INT DEFAULT 60 COMMENT '服务时长（分钟）',
  `contact_name` VARCHAR(50) COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) COMMENT '联系人电话',
  `remark` TEXT COMMENT '备注',
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  `discount_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '优惠金额',
  `actual_amount` DECIMAL(10,2) NOT NULL COMMENT '实付金额',
  `coupon_id` BIGINT COMMENT '优惠券ID',
  `status` TINYINT DEFAULT 1 COMMENT '状态：1-待支付，2-待服务，3-服务中，4-待评价，5-已完成，6-已取消，7-已退款',
  `cancel_reason` VARCHAR(255) COMMENT '取消原因',
  `cancel_time` DATETIME COMMENT '取消时间',
  `start_time` DATETIME COMMENT '开始服务时间',
  `end_time` DATETIME COMMENT '结束服务时间',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_order_no (`order_no`),
  INDEX idx_user_id (`user_id`),
  INDEX idx_worker_id (`worker_id`),
  INDEX idx_status (`status`),
  INDEX idx_service_time (`service_time`),
  INDEX idx_order_user_status_time (`user_id`, `status`, `created_at`),
  INDEX idx_order_worker_status_time (`worker_id`, `status`, `created_at`),
  INDEX idx_order_created_status (`created_at`, `status`),
  INDEX idx_order_trend (`created_at`, `status`, `actual_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';